### ISSUE TITLE
Feat: Permit watch only current path or its childs.

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/funzzy#1]
Concat current folder with watched folder for matching.
```yaml
- name: run tests
  when: 
    change: 'tests/**'
    run: make tests
```
That way avoiding that strange `**/somenthin/**` that is ugly.
