### ISSUE TITLE
fix: missing {{filepath}} when using run_on_init

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/funzzy#103]
## How to reproduce
This config
```yaml
- name: run formatter (tag:quick)
  run: "cargo fmt -- {{filepath}}"
  change: "src/**"
  ignore: "src/**/*log*"
  run_on_init: true
```
Run 
```
fzz
// Funzzy: cargo fmt -- {{filepath}}
//
// Error: file `{{filepath}}` does not exist

```
