### ISSUE TITLE
feat: allow reading environment variables for paths

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/funzzy#159]
Just an idea I had while having to debug nix builds and there was issues with permissions

```yaml
- name: task with absolute path @valid
  run:
    - "echo 'this file has changed: {{filepath}}'"
  change: 
    - "/tmp/fzz/accepts_full_or_relativepaths.txt"
    - "/tmp/fzz/accepts_full_or_relativepaths2.txt"
    - "examples/workdir/**/*"
  ignore: 
    - "examples/workdir/ignored/**/*.txt"
```

And I would like to set env virable to watch different paths
```yaml
- name: task with absolute path @valid
  run:
    - "echo 'this file has changed: {{filepath}}'"
  change: 
    - "$MY_CUSTOM_PATH/fzz/accepts_full_or_relativepaths.txt"
    - "{{MY_VARIABLE?}}/fzz/accepts_full_or_relativepaths2.txt"
    - "examples/workdir/**/*"
  ignore: 
    - "examples/workdir/ignored/**/*.txt"

```
