### ISSUE TITLE
fix: better message when yaml file has bad format.

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/funzzy#16]
Today when yaml has bad format we get this error:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: ScanError { mark: Marker { index: 222, line: 10, col: 4 }, info: "while parsing a flow sequence, expectd \',\' or \']\'" }', ../src/libcore/result.rs:688
```

We need a better error message.

**Comment by cristianoliveira** [comment]
Example of a bad format:
```yaml
## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute

- name: run my tests
  when:
    change: ['lib/**', 'spec/**'
    run: make test
```
