### ISSUE TITLE
feat: propose of new yaml format.

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/funzzy#17]
Make more sense if `run:` be at same level of `when:` 
example:
```yaml
- name: run my tests
  run: make test
  when:
    change: ['lib/**', 'spec/**']
    ignore: 'tmp/**'
```
