### ISSUE TITLE
fix: when loading yaml without explicity string

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/funzzy#180]
eg
```yaml
- name: adds to git
  run_on_init: true
  run:
    - git add {{relative_filepath}}
    - git add -p
    - git fetch && git rebase origin/main
  change: 
    - .fzz/git-task # touch .fzz/git-task
    - **/* ## THIS
  ignore:
    - git/**/*
    - result
```
