### ISSUE TITLE
feat: common rules among the tasks

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/funzzy#195]
I get myself having to repeat (mostly) similar `change` and `ignore` for many rules in a workflow. I wonder if I could add something like 
```yaml
on:
  change:
     - 'foobar/**'
     - 'bar.js'
  ignore:
     - '**/*.log'

tasks:
  ## .. standard config
```
