### ISSUE TITLE
feat: allows setting a working dir

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/funzzy#196]
This is a need that I feel everytime I need to work with monorepos, sometimes adapting the scripts to run from the root folder takes longer than just running funzzy inside of each project

```yaml
 - name: setup install
  workdir: ./myapp/ # This would be similar to `cd ./myapp/ && npm install`
  run: npm install
  run_on_init: true
  change: package.json
```
