### ISSUE TITLE
feat: allows rule without `change` property

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/funzzy#197]
There are tasks that are run only once the workflow is initialized. An example of something that I use is to open `npm run playwright -- --ui` that opens, and keep opened, the playwright interface while funzzy is running

**Comment by cristianoliveira** [comment]
Today I achieve that with:
```yaml
- name: run tests @quick @vim
  run: 'nrr e2e --ui &'
  change: '__noop__'
  run_on_init: true
```
