### ISSUE TITLE
feat: run specific tasks as services

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/funzzy#229]
Sometimes I have to open some app or long-lived process in my workflow as part of a bigger workflow but I want it to behave more like a local service that once something change it is restarted.

 Ex on how I achieve that today:
```yaml
- name: run fe app
  run: cd web && yarn dev --watch & # This runs on background
  run_on_init: true

- name: run golang app
  run: 
    - pkill mobile-payments-web || true
    - make run-backend &
  change: '**/*.go'
  run_on_init: true
  # Maybe here goes a `service: true`

- name: run tests app
  run:  make tests
  change: '**/*.go'
  run_on_init: true
````
