### ISSUE TITLE
No working with VScode

### ISSUE THREAD

**Issue by Mgldvd** [cristianoliveira/funzzy#68]
Hi, I'm not sure if this is out of scope. 
Is working fine with `vim` or the default visual editor on the os but not working with editor like `vscode`, `pulsar editor` or `sublime text`
also not working with `nano`
the output is just 
`Funzzy: Watching...`
I'm using `Linux mint` as OS

Here the yml file:

```yml
- name: run my test
  run: [
    'ls -a',
    'echo helooooo'
  ]
  change: "**"
```

also i want to point out that `inotifywait` is working fine:

```bash
while inotifywait -e close_write **; \
do clear && \
    date +"%T"
    ls -la
done
```

Any idea? Thank you
