### ISSUE TITLE
bug: cli panic when scaping chars 

### ISSUE THREAD

**Issue by cristianoliveira** [cristianoliveira/funzzy#85]
Try this:
```yaml
- name: run tests
  run: ["yarn test {{filepath}}", "echo '{{filepath}}' | sed -r 's\/.tsx/\/'" ]
  change: 'src/**'
```

And once the cli attempts to load the rules it panics:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ScanError { mark: Marker { index: 258, line: 8, col: 34 }, info: "while parsing a quoted scalar, found unknown escape character" }', src/rules.rs:92:57
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: fzz::rules::from_file
   4: fzz::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
